function bind(func,target){return function(){if(func.apply){func.apply(target,arguments);}else{}};}
function wp_log(msg){return;if(window.console&&window.console.log)
window.console.log(msg);}
function WPApp(){this.blog_url='http://en.blog.wordpress.com/';this.owner=null;this.owner_id=null;this.viewer=null;this.viewer_id=null;this.wpcom_api='http://wordpress.com/gadgets/wp-os.php';this.domain=null;this.nwu_post=null;this.callGetOwnerStuff();}
WPApp.prototype.isOwner=function(){return(this.owner_id&&this.owner_id==this.viewer_id);};WPApp.prototype.callGetOwnerStuff=function(){var req=opensocial.newDataRequest();this.domain=opensocial.getEnvironment().getDomain();req.add(req.newFetchPersonRequest(opensocial.IdSpec.PersonId.OWNER),'owner');req.add(req.newFetchPersonRequest(opensocial.IdSpec.PersonId.VIEWER),'viewer');req.send(bind(this.handleReturnedData,this));}
WPApp.prototype.handleReturnedData=function(retDataObject){if(retDataObject&&!retDataObject.hadError()){if(!retDataObject.get('owner').hadError()){this.owner=retDataObject.get('owner').getData();this.owner_id=this.owner.getField('id');}
if(!retDataObject.get('viewer').hadError()){this.viewer=retDataObject.get('viewer').getData();this.viewer_id=this.viewer.getField('id');}}
else{wp_log('error in handleReturnedData');wp_log(retDataObject.getErrorMessage());wp_log(retDataObject.get('owner').getErrorMessage());wp_log(retDataObject.get('viewer').getErrorMessage());}
this.showBlog();}
WPApp.prototype.showConfig=function(){wp_log('showConfig');if(this.isOwner()){document.getElementById('wp_config').style.display='block';show_link=document.getElementById('wp_config_show_link');show_link.style.display='inline';show_link.onclick=bind(this.hideConfig,this);}}
WPApp.prototype.hideConfig=function(){wp_log('hideConfig');document.getElementById('wp_config').style.display='none';if(this.isOwner()){show_link=document.getElementById('wp_config_show_link')
show_link.style.display='inline';show_link.onclick=bind(this.showConfig,this);}}
WPApp.prototype.showBlog=function(){wp_log('WPApp.showBlog');var params={};params[gadgets.io.RequestParameters.CONTENT_TYPE]=gadgets.io.ContentType.JSON;params[gadgets.io.RequestParameters.AUTHORIZATION]=gadgets.io.AuthorizationType.NONE;var url=this.wpcom_api;url+='?wp_os_owner_id='+this.owner_id;url+='&app='+escape(this.domain);if(this.isOwner()){var ts=new Date().getTime();url+='&ts='+ts;}
gadgets.io.makeRequest(url,bind(this.showBlogResponse,this),params);};WPApp.prototype.showBlogResponse=function(obj){wp_log('showBlogResponse');wp_log(obj);if(obj==undefined||obj.data==undefined){if(obj.errors.length)
msg='Sorry, unable to fetch your blog ('+obj.errors+').  Please try again later!';else
msg='Sorry, unable to fetch your blog.  Please try again later!';wp_log(msg);document.getElementById('wp-os-content').innerHTML='<p>'+msg+'</p>';this.showConfig();return;}
var jsondata=obj.data;var html='';var head='';var blog_url=jsondata['blog_url'];var blog_name=jsondata['blog_name'];var config_url=jsondata['config_url'];var linkedin_tag=jsondata['linkedin_tag'];var network_update_ts=jsondata['network_update_ts'];var appname=jsondata['filter_tag'];head+='<div class="wp_head"><div class="wp_head_wrap">';head+='<h1 class="wp_blog_title"><a href="'+gadgets.util.escapeString(blog_url)+'" target="_blank">'+gadgets.util.escapeString(blog_name)+'</a></h1>';if(this.isOwner())
head+='<a href="javascript:void(0);" id="wp_config_show_link">[edit]</a>';head+='<a href="http://wordpress.com/signup/?ref='+appname+'" class="wp_logo" target="_blank"><img src="http://s.wordpress.com/gadgets/icon-1.png" title="Get a free blog at WordPress.com" /></a>';head+='</div></div>';html+='<div id="wp_body">';var last_avatar=0;for(var key in jsondata['blog_posts']){post=jsondata['blog_posts'][key];this.checkBlogUpdated(network_update_ts,post);html+='<div class="wp_post">';if(post['avatar']!=last_avatar)
html+='<img src="'+gadgets.util.escapeString(post['avatar'])+'" width=32 height=32 class="wp_avatar" />';last_avatar=post['avatar'];html+='<h3 class="wp_post_title"><a href="'+gadgets.util.escapeString(post['permalink'])+'" class="wp_post_title" target="_blank">'+gadgets.util.escapeString(post['title'])+'</a></h3>';html+=' <span class="wp_post_date">'+gadgets.util.escapeString(post['date'])+'</span>';html+='<p class="wp_post_excerpt">'+post['excerpt']+'</p>';html+='</div>';}
html+='<img src="http://stats.wordpress.com/b.gif?v=lin&amp;rand='+Math.random()+'" />';html+='</div>';document.getElementById('wp_top').innerHTML=head;document.getElementById('wp-os-content').innerHTML=html;document.getElementById('wp_blog_url').value=config_url;var tagname_el=document.getElementById('tagname');if(tagname_el&&appname)
tagname_el.innerHTML=appname;if(linkedin_tag)
document.getElementById('wp_tag_filter_linkedin').checked=true;else
document.getElementById('wp_tag_filter_all').checked=true;if(document.getElementsByTagName){var signupRef=document.getElementById('wp_blog_form').getElementsByTagName('a');wp_log(signupRef);if(signupRef.length&&signupRef[0].setAttribute&&signupRef[0].getAttribute&&signupRef[0].hasAttribute&&signupRef[0].hasAttribute('href')){for(var i=0;i<signupRef.length;i++){signupRef[i].setAttribute('href',signupRef[i].getAttribute('href').replace('ref=opensocial','ref='+appname));}}}
if(config_url==undefined||config_url.length==0){document.getElementById('wp_error_message').innerHTML=jsondata['error'];if(this.isOwner()){gadgets.window.adjustHeight(200);this.showConfig();}else{gadgets.window.adjustHeight(0);}}
else{this.hideConfig();gadgets.window.adjustHeight(500);if(gadgets.window&&gadgets.window.setTitle)
gadgets.window.setTitle('WordPress');dims=gadgets.window.getViewportDimensions();document.getElementById('wp_body').style.width=dims.width;}};WPApp.prototype.setBlogURL=function(blog_url,linkedin_tag){var params={};params[gadgets.io.RequestParameters.CONTENT_TYPE]=gadgets.io.ContentType.JSON;params[gadgets.io.RequestParameters.AUTHORIZATION]=gadgets.io.AuthorizationType.SIGNED;var url=this.wpcom_api;url+='?wp_blog_url='+escape(blog_url);url+='&app='+escape(this.domain);url+='&linkedin_tag='+Number(linkedin_tag);gadgets.io.makeRequest(url,bind(this.setBlogURLResponse,this),params);};WPApp.prototype.setBlogURLResponse=function(obj){if(obj==undefined||obj.data==undefined){wp_log('setBlogURLResponse is empty');if(console.dir)
console.dir(obj)
return;}
var jsondata=obj.data;var html="<strong>setBlogURL response: </strong><br /><br />";html+='<pre>'+obj.text+'</pre>';document.getElementById('wp_blog_url').value=jsondata['config_url'];document.getElementById('wp_error_message').innerHTML=jsondata['error'];if(jsondata['config_url'].length>0)
this.showBlog();};WPApp.prototype.checkBlogUpdated=function(network_update_ts,post){if(this.owner_id!=this.viewer_id)
return;if(this.nwu_post)
return;if(post['timestamp']<=network_update_ts)
return;wp_log('checkBlogUpdated running for '+post['permalink']);wp_log('checkBlogUpdated post timestamp is '+post['timestamp']);this.nwu_post=post;this.setBlogUpdated();}
WPApp.prototype.updateNetwork=function(postTitle,postUrl,postExcerpt){wp_log('updateNetwork');wp_log('title = '+postTitle);wp_log('url = '+postUrl);var profileName=this.owner.getDisplayName();var profileUrl=this.owner.getField("profileUrl");var profileHref=linkTo(profileUrl,profileName);var blogHref=linkTo(postUrl,postTitle);var updateString=profileHref+" has a new blog post: "+blogHref+" posted with WordPress";wp_log('updatestring is '+updateString);var updateParams={};wp_log(postExcerpt);wp_log(postExcerpt.replace(/<div[\s\S]*$/,'[video]'));updateParams[opensocial.Activity.Field.BODY]=updateString+"\n\n"+postExcerpt.replace(/<div[\s\S]*$/,'[video]');var activity=opensocial.newActivity(updateParams);wp_log(activity);opensocial.requestCreateActivity(activity,opensocial.CreateActivityPriority.HIGH,bind(this.updateNetworkCallback,this));};WPApp.prototype.updateNetworkCallback=function(updateStatus){wp_log('updateNetworkCallback');if(!updateStatus.hadError()){wp_log('update succeeded!');}
else{wp_log('error is '+updateStatus.getErrorMessage());}}
WPApp.prototype.setBlogUpdated=function(){if(this.viewer_id!=this.owner_id)
return;when=this.nwu_post['timestamp'];wp_log('setBlogUpdated ts='+when);var params={};params[gadgets.io.RequestParameters.CONTENT_TYPE]=gadgets.io.ContentType.JSON;params[gadgets.io.RequestParameters.AUTHORIZATION]=gadgets.io.AuthorizationType.SIGNED;var url=this.wpcom_api;url+='?network_update_ts='+when;url+='&app='+escape(this.domain);gadgets.io.makeRequest(url,bind(this.setBlogUpdatedResponse,this),params);}
WPApp.prototype.setBlogUpdatedResponse=function(response){wp_log('setBlogUpdatedResponse: '+response.text);if(response&&response.data){wp_log('setBlogUpdatedResponse ts is '+response.data['network_update_ts']);wp_log('nwu_post timestamp is '+this.nwu_post['timestamp']);if(response.data['network_update_ts']==this.nwu_post['timestamp']){wp_log('issuing update');this.updateNetwork(this.nwu_post['title'],this.nwu_post['permalink'],this.nwu_post['excerpt']);}}}
function linkTo(href,text){return"<a href='"+href+"'>"+gadgets.util.escapeString(gadgets.util.unescapeString(text))+"</a>";};function addEventHandler(node,eventName,eventHandler)
{var CAPTURING_PHASE=true,BUBBLING_PHASE=false;if(node.addEventListener)
{node.addEventListener(eventName,eventHandler,BUBBLING_PHASE);}
else if(node.attachEvent)
{node.attachEvent('on'+eventName,eventHandler);}}
function wp_init(){wp_log('in wp_init');wpapp=new WPApp();}
function saveURL(){var url=document.getElementById('wp_blog_url').value;var linkedin_tag=document.getElementById('wp_tag_filter_linkedin').checked;wpapp.setBlogURL(url,linkedin_tag);}
function handleKeyPress(e){var key=e.keyCode||e.which;if(key==13){saveURL();return false;}
return true;}